### ISSUE TITLE
Care releasing the 1.2.5 version

### ISSUE THREAD

**Issue by furtabs** [Quintinity/MobCages#10]

**Comment by vladmarica** [comment]
Unfortunately, the source code for the 1.2.5 version is lost. This version was rewritten from scratch, keeping only the cage model. Sorry!

**Comment by furtabs** [comment]
Since you kept the model do you have the compiled jar. I can make some magic happen if I can have the jar

**Comment by vladmarica** [comment]
I do not have the .jar. I copied the model code and deleted the old code after the port. This happened 7 years ago.
